#!/usr/bin/env perl
use 5.024;
use warnings;
use Sys::Hostname;
use Email::MIME;

my $maildir = shift;
die "No maildir\n" unless $maildir;

# create email from STDIN
my $email = Email::MIME->new(
    do { local $/; <>; }
);

# parse the message body for useful information
my $attached = ( $email->subparts )[1];

# dump the email in Maildir 
my $file = sprintf "%s/new/%d.%d_%d.%s",
   $maildir, time, $$, 1245, hostname;
open my $fh, '>', $file or die "Can't open $file for saving\n";
print $fh $attached->body;

say "Saved message to $file";
