#!/usr/bin/env perl
use 5.024;
use warnings;
use Email::MIME;

# create email from STDIN
my $email = Email::MIME->new(
    do { local $/; <>; }
);

# parse the message body for useful information
my $body = $email->body;
my ( $address, @missing );

for ( split /\n/, $body ) {
    if ( /Here are the message numbers:/ .. /--- Enclosed/ and /(\d+)/ ) {
        my $num = $1;
        my $cmd = qq{mutt -s "get $num" $address} =~ s/123_145/$num/r;
        say "Request message $num from $address" =~ s/123_145/$num/r;
        `$cmd </dev/null`;
    }
    elsif (m{<([^>]+-get\.123_145\@[^>]+)>}) {
        $address = $1;
    }
}
